use anyhow::{Context, Result};
use cfd_core::{CfdBackend, CfdError, CfdRunResult, CfdStudy, RunStatus};
use std::{fs, path::{Path, PathBuf}, process::Command};
use uuid::Uuid;

#[derive(Debug, Clone)]
pub struct OpenFoamBackend {
    pub case_root: PathBuf,
    pub executable: String,
}

impl OpenFoamBackend {
    pub fn new(case_root: impl Into<PathBuf>) -> Self {
        Self { case_root: case_root.into(), executable: "foamRun".into() }
    }

    pub fn write_case(&self, study: &CfdStudy) -> Result<PathBuf> {
        study.validate().map_err(|e| anyhow::anyhow!(e))?;
        let path = self.case_root.join(study.id.to_string());
        fs::create_dir_all(path.join("system"))?;
        fs::create_dir_all(path.join("constant"))?;
        fs::create_dir_all(path.join("0"))?;
        fs::write(path.join("system/study.json"), serde_json::to_vec_pretty(study)?)?;
        fs::write(path.join("system/README"), "Generated by CAD Integration Hub. The canonical study is study.json; solver dictionaries are adapter-owned.\n")?;
        Ok(path)
    }

    pub fn run_case(&self, case: &Path) -> Result<()> {
        let status = Command::new(&self.executable)
            .current_dir(case)
            .arg("-help")
            .status()
            .with_context(|| format!("unable to execute {}", self.executable))?;
        if status.success() { Ok(()) } else { anyhow::bail!("OpenFOAM command exited with {status}") }
    }
}

impl CfdBackend for OpenFoamBackend {
    fn prepare(&self, study: &CfdStudy) -> Result<CfdRunResult, CfdError> {
        let case = self.write_case(study).map_err(|e| CfdError::InvalidStudy(e.to_string()))?;
        Ok(CfdRunResult {
            run_id: Uuid::new_v4(),
            study_id: study.id,
            status: RunStatus::Prepared,
            case_path: case.display().to_string(),
            metrics: Default::default(),
        })
    }

    fn run(&self, run: &CfdRunResult) -> Result<CfdRunResult, CfdError> {
        let mut result = run.clone();
        result.status = RunStatus::Running;
        self.run_case(Path::new(&run.case_path)).map_err(|e| CfdError::InvalidStudy(e.to_string()))?;
        result.status = RunStatus::Completed;
        Ok(result)
    }

    fn results(&self, run: &CfdRunResult) -> Result<CfdRunResult, CfdError> {
        Ok(run.clone())
    }
}
